var dir_22e14a881477d9a3aee7abf9a39f7d06 =
[
    [ "grids.cpp", "grids_8cpp.html", "grids_8cpp" ],
    [ "grids.h", "grids_8h.html", "grids_8h" ],
    [ "hoccontext.h", "hoccontext_8h.html", "hoccontext_8h" ],
    [ "inithoc.cpp", "inithoc_8cpp.html", "inithoc_8cpp" ],
    [ "nrnpy_hoc.cpp", "nrnpy__hoc_8cpp.html", "nrnpy__hoc_8cpp" ],
    [ "nrnpy_hoc_2.h", "nrnpy__hoc__2_8h.html", "nrnpy__hoc__2_8h" ],
    [ "nrnpy_hoc_3.h", "nrnpy__hoc__3_8h.html", "nrnpy__hoc__3_8h" ],
    [ "nrnpy_nrn.cpp", "nrnpy__nrn_8cpp.html", "nrnpy__nrn_8cpp" ],
    [ "nrnpy_nrn_2.h", "nrnpy__nrn__2_8h.html", "nrnpy__nrn__2_8h" ],
    [ "nrnpy_nrn_3.h", "nrnpy__nrn__3_8h.html", "nrnpy__nrn__3_8h" ],
    [ "nrnpy_p2h.cpp", "nrnpy__p2h_8cpp.html", "nrnpy__p2h_8cpp" ],
    [ "nrnpy_reg.h", "nrnpy__reg_8h.html", "nrnpy__reg_8h" ],
    [ "nrnpy_utils.h", "nrnpy__utils_8h.html", "nrnpy__utils_8h" ],
    [ "nrnpython.cpp", "nrnpython_8cpp.html", "nrnpython_8cpp" ],
    [ "nrnpython.h", "nrnpython_8h.html", "nrnpython_8h" ],
    [ "nrnwrap_Python.h", "nrnwrap___python_8h.html", null ],
    [ "rxd.cpp", "rxd_8cpp.html", "rxd_8cpp" ],
    [ "rxd.h", "rxd_8h.html", "rxd_8h" ],
    [ "rxd_extracellular.cpp", "rxd__extracellular_8cpp.html", "rxd__extracellular_8cpp" ],
    [ "rxd_intracellular.cpp", "rxd__intracellular_8cpp.html", "rxd__intracellular_8cpp" ],
    [ "rxd_llgramarea.c", "rxd__llgramarea_8c.html", "rxd__llgramarea_8c" ],
    [ "rxd_marching_cubes.c", "rxd__marching__cubes_8c.html", "rxd__marching__cubes_8c" ],
    [ "rxd_vol.cpp", "rxd__vol_8cpp.html", "rxd__vol_8cpp" ],
    [ "rxdmath.c", "rxdmath_8c.html", "rxdmath_8c" ]
];